In [1]:
#import numpy library
import numpy as np

In [3]:
#create 1D array 
arr_1d=np.array([1,2,3,4])
print(arr_1d)

[1 2 3 4]


In [3]:
#Check the type of Array (whether it is an array or list) we use type().
type(arr_1d)

numpy.ndarray

In [4]:
#Check dimension of Array(1d or 2d or 3d) we use .ndim
arr_1d.ndim


1

In [5]:
# Create 2-D Array
arr_2d=np.array([[1,2,3,4],[5,6,7,8]])
print(arr_2d)

[[1 2 3 4]
 [5 6 7 8]]


In [6]:
#Check dimension of Array(1d or 2d or 3d) we use .ndim
arr_2d.ndim

2

In [7]:
#Check the size of 1D Array we use .size

arr_1d.size

4

In [8]:
#Check the size of 2D Array we use .size

arr_2d.size

8

In [9]:
#Check the shape of 2D Array we use .shape(How many rows and columns) we use .shape
arr_2d.shape

(2, 4)

In [10]:
#Check datatype of 2D Array we use .dtype
arr_2d.dtype


dtype('int32')

In [11]:
#print 2d array
arr_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
arr_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])