In [9]:
import numpy as np

In [10]:
arr = np.arange(0,11)

In [11]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
# check the elment position simply

arr[7]


7

In [13]:
# slicing
arr[0:4]

array([0, 1, 2, 3])

In [14]:
arr[0:5]=100

In [15]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [16]:
arr=np.arange(0,11)

In [17]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
slice_of_arr= arr[0:6]

In [19]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [23]:
# when u want to broadcast or chahnge it to diff num , it affects the orgnl array

In [25]:
slice_of_arr[:] = 99

In [26]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [27]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [4]:
import numpy as np

In [8]:
arr_2d = np.array([[20,49,59],[70,80,90],[50,80,30]])

In [9]:
arr_2d

array([[20, 49, 59],
       [70, 80, 90],
       [50, 80, 30]])

In [10]:
arr_2d[0,0]

20

In [12]:
arr_2d[1][2]

90

In [15]:
arr_2d[1]

array([70, 80, 90])

In [16]:
arr_2d[:2,1:]

array([[49, 59],
       [80, 90]])

In [18]:
arr = np.arange(1,11)

In [19]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
# comparison operators
arr < 5

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [22]:
bool_arr = arr < 5

In [23]:
bool_arr

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [24]:
# gettng an array and using comparison oprtr with it will return boolean array
arr[bool_arr]

array([1, 2, 3, 4])

In [34]:
# for practice

arr_2d = np.arange(50).reshape(5,10)

In [35]:
arr_2d


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [37]:
arr_2d[2:4,2:4]

array([[22, 23],
       [32, 33]])

In [2]:
# practice 
import numpy as np
arr_3d = np.array([[40,50,60],[70,80,90],[35,45,55]])

In [3]:
arr_3d

array([[40, 50, 60],
       [70, 80, 90],
       [35, 45, 55]])

In [7]:
arr_3d = np.arange(30).reshape(3,10)

In [8]:
arr_3d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [10]:
np.zeros(2)

array([0., 0.])

In [11]:
arr_3d.argmax()

29

In [13]:
arr_3d.argmin()

0

In [18]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [24]:
arr_4d = np.arange(5,50,5),(9,30,3)

In [25]:
arr_4d

(array([ 5, 10, 15, 20, 25, 30, 35, 40, 45]), (9, 30, 3))

In [35]:
arr_4d = np.linspace(2,20,1)

In [36]:
arr_4d

array([2.])

In [38]:
arr_4d.argmin()

0

In [40]:
arr_4d[1:2]

array([], dtype=float64)