In [1]:
import numpy as np

In [2]:
#create ones matrix
mx_1s = np.array([[1,1,1],[1,1,1],[1,1,1]])
print(mx_1s)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


# ones function

In [3]:
# use ones function create matrix
np.ones(1)

array([1.])

In [4]:
# assign Variable name to the function
mx_1s =np.ones(1)
print(mx_1s)

[1.]


In [5]:
#check the data type of matrix
mx_1s.dtype

dtype('float64')

In [6]:
#Create ones function with row and columns
mx_1s = np.ones((3,4))
print(mx_1s)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [7]:
#Create ones function with integer Value
mx_1s = np.ones((3,4),dtype=int)
print(mx_1s)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [8]:
#Create zeros matrix using zero()
mx_1s = np.zeros((3,4),dtype=int)
print(mx_1s)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [9]:
# return bool datatype
mx_1s = np.zeros((3,4),dtype=bool)
print(mx_1s)

[[False False False False]
 [False False False False]
 [False False False False]]


In [10]:
#return string datatype
mx_1s = np.zeros((3,4),dtype=str)
print(mx_1s)

[['' '' '' '']
 ['' '' '' '']
 ['' '' '' '']]


In [11]:
#return empty matrix
mx_1s=np.empty((3,3))
print(mx_1s)

[[3.23786e-319 0.00000e+000 0.00000e+000]
 [0.00000e+000 0.00000e+000 3.47822e-321]
 [0.00000e+000 0.00000e+000 0.00000e+000]]


# Numpy Function:

In [12]:
import numpy as np

# arange()

In [13]:
#np.arange(start_value,End_value,steps)
ar_1d = np.arange(1,13)
print(ar_1d)



[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [14]:
odd_ar = np.arange(1,33,2)
print(odd_ar)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31]


# linspace()

In [15]:
np.linspace(1,5,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

# reshape()

In [16]:
# convert 1d array into 2d array and 3d array

ar_2d = ar_1d.reshape(2,6)
print(ar_2d)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [17]:
ar_2d = ar_1d.reshape(3,4)
print(ar_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [18]:
#convert 1d array into 3d array
ar_3d = ar_2d.reshape(2,3,2)
print(ar_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [19]:
# create 2d matrix in one line using reshape function
ar = np.arange(1,13).reshape(2,6)
print(ar)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


# ravel()

In [20]:
#convert Multidimentional array into 1d array
ar.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# flatten()

In [21]:
# convert Multidimentional array into 1d array
ar.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# transpose()

In [22]:
ar.transpose()

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])

In [23]:
# you can also use T function
ar.T

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])

# Mathematic Operation Using Numpy