In [1]:
# cast norml pythn list into arrays

In [2]:
my_lst = [1,2,3]

In [3]:
import numpy as np

In [4]:
arr = np.array(my_lst)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_str =("abc,xyz")

In [7]:
arr = np.array(my_str)

In [8]:
arr

array('abc,xyz', dtype='<U7')

In [9]:
my_dict= {'k1':'value1','k2':'value2'}

In [45]:
my_dict.keys()

dict_keys(['k1', 'k2'])

In [46]:
my_dict.values()

dict_values(['value1', 'value2'])

In [11]:
arr = np.array(my_dict)

In [12]:
arr

array({'k1': 'value1', 'k2': 'value2'}, dtype=object)

In [13]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [14]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
import numpy as np
# two brackets means two d array

In [16]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [17]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
np.arange(0,11,2)
# start,stop,step

array([ 0,  2,  4,  6,  8, 10])

In [19]:
np.zeros(3)

array([0., 0., 0.])

In [20]:
np.zeros(2)

array([0., 0.])

In [21]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
np.ones(4)

array([1., 1., 1., 1.])

In [23]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [47]:
np.linspace(0,5,10)
# start,stop,no of points u want

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [49]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [50]:
# identity matrix rows = col and means diagonl of 1 and evrythng else = 0

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [51]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
# random numbers = random values in given shape most common method in uniform distribution
np.random.rand(4)

array([0.2278994 , 0.36079526, 0.44058453, 0.32810045])

In [27]:
np.random.rand(1,4)

array([[0.08480573, 0.97034362, 0.30070831, 0.69190518]])

In [28]:
# np.random.randn() = random values in norml distribution
np.random.randn(2)

array([0.14802681, 0.84625341])

In [53]:
# np.randomint()
# from -to-no of int wanted
np.random.randint(1,100)

5

In [54]:
np.random.randint(2,50)

38

In [30]:
np.random.randint(1,50,10)

array([33,  6, 27, 41,  5, 29, 40, 15,  9,  1])

In [31]:
# creating two array objects

arr = np.arange(25)

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [33]:
ranarr = np.random.randint(2,8,4)

In [34]:
ranarr

array([7, 5, 4, 3])

In [35]:
# reshape method = Returns an array containing the same data with a new shape.
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [36]:
# max,min = return mac and min value of an array
ranarr.max()

7

In [37]:
ranarr.min()

3

In [38]:
# check location of elemnt by
#argmax,argmin

ranarr.argmax()

0

In [39]:
ranarr.argmin()

3

In [40]:
# shape and reshape method .shape,.reshape()
arr.shape

(25,)

In [41]:
# reshape()
arr = arr.reshape(5,5)

In [42]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [43]:
arr.shape

(5, 5)

In [44]:
# check the data type 
arr.dtype

dtype('int32')